config_root:
  alias: host
  platform: linux

  proj_path: { from: env, name: PROJ_PATH }
  config_path: { from: env, name: CONFIG_PATH }
  config_name: { from: env, name: CONFIG_NAME }

  py_ver: { from: env, name: PY_VER }
  env_name: { from: env, name: ML_VENV_NAME }

  inner:
    alias: podman
    runtime: podman
    platform: linux

    # unused
    image: ubuntu:22.04

    extra_preapt_commands:
    - RUN dpkg --add-architecture i386

    apt_packages:
    - graphviz
    - flatbuffers-compiler
    - protobuf-compiler
    - cmake
    - build-essential
    - wine
    - wine32
    - wine64
    - wget
    - ca-certificates

    extra_podman_run_commands:
    - RUN wineboot --init
    - '[ ! -e "${PROJ_PATH}/${CRI_HOME}/python-3.9.13-embed-amd64.zip" ] && wget -O "${PROJ_PATH}/${CRI_HOME}/python-3.9.13-embed-amd64.zip" https://www.python.org/ftp/python/3.9.13/python-3.9.13-embed-amd64.zip'
    - '[ ! -e "${PROJ_PATH}/${CRI_HOME}/get-pip.py" ] && wget -O "${PROJ_PATH}/${CRI_HOME}/get-pip.py" https://bootstrap.pypa.io/pip/3.9/get-pip.py'
    - unzip -o "${PROJ_PATH}/${CRI_HOME}/python-3.9.13-embed-amd64.zip" -d "${PROJ_PATH}/${CRI_HOME}/.wine/drive_c/Python39/"
    - RUN wine ${CRI_PROJ_PATH}/${CRI_HOME}/.wine/drive_c/Python39/python.exe ${CRI_PROJ_PATH}/${CRI_HOME}/get-pip.py
    - echo sed -i 's/#import site/import site/' ${PROJ_PATH}/${CRI_HOME}/.wine/drive_c/Python39/python39._pth
    - sed -i 's/#import site/import site/' ${PROJ_PATH}/${CRI_HOME}/.wine/drive_c/Python39/python39._pth
    - RUN wine reg add 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' /v Path /t REG_EXPAND_SZ /d 'C:\Python39;C:\Python39\Scripts' /f    
    - RUN wineserver --wait

    ps1_tag: { from: env, name: PS1_TAG }
    cri_home: { from: env, name: CRI_HOME }
    cri_root: { from: env, name: CRI_ROOT }
    cri_bin: { from: env, name: CRI_BIN }
    cri_run: { from: env, name: CRI_RUN }
    cri_run_args: { from: env, name: CRI_RUN_ARGS }
    cri_proj_path: { from: env, name: CRI_PROJ_PATH }

    # TODO: Rethink how to push venv initialization into venv runtime.
    # TODO: Re-do download-all-deps so its coming from wine python.
    # TODO: Re-do build-venv so its using wine python.
    # TODO: Re-do start-venv so its using cmd.exe or something.

    python: { from: env, name: PYTHON }
    pip_idx_args: { from: env, name: PIP_IDX_ARGS }
    pip_upstream_verifiers: { from: env, name: PIP_UPSTREAM_VERIFIERS }
    venv_python: { from: env, name: VENV_PYTHON }
    py_constraints: { from: env, name: PY_CONSTRAINTS }
    py_reqs: { from: env, name: PY_REQS }
    pkg_skip_list: { from: env, name: PKG_SKIP_LIST }

    inner:
        runtime: venv
        path: /opt/myenv
        packages: [numpy, pandas]