config_root:
  alias: host
  builder: host
  platform: linux
  init: init-host.sh

  proj_path: { from: env, name: PROJ_PATH }
  config_path: { from: env, name: CONFIG_PATH }
  config_name: { from: env, name: CONFIG_NAME }

  py_ver: { from: env, name: PY_VER }
  env_name: { from: env, name: ENV_NAME }

  inner:
    alias: conda
    builder: conda
    init: init-conda.sh
    run: run-conda.sh

    python: { from: env, name: SYSTEM_PYTHON }
    cached_conda_prefix: { from: env, name: CACHED_CONDA_PREFIX }
    pip_version_spec: { from: env, name: PIP_VERSION_SPEC }

    inner:
      alias: python
      builder: python
      platform: linux
      init: init-python.sh

      root_drive: { from: env, name: ROOT_DRIVE }
      python_pkg_path: { from: env, name: PYTHON_PKG_PATH }
      python_autoinstall_path: { from: env, name: PYTHON_AUTOINSTALL_PATH }

      ps1_tag: { from: env, name: PS1_TAG }
      python: { from: env, name: CACHED_CONDA_PYTHON }
      pip_idx_args: { from: env, name: PIP_IDX_ARGS }
      pip_upstream_verifiers: { from: env, name: PIP_UPSTREAM_VERIFIERS }
      py_constraints: { from: env, name: PY_CONSTRAINTS }
      py_reqs: { from: env, name: PY_REQS }
      pkg_skip_list: { from: env, name: PKG_SKIP_LIST }

