config_root:
  alias: host
  builder: host
  platform: linux
  init: init-host.sh

  proj_path: { from: env, name: PROJ_PATH }
  config_path: { from: env, name: CONFIG_PATH }
  config_name: { from: env, name: CONFIG_NAME }

  py_ver: { from: env, name: PY_VER }
  env_name: { from: env, name: ENV_NAME }

  inner:
    alias: podman
    builder: podman
    platform: linux
    init: init-podman.sh
    run: run-podman.sh

    # unused; image: ubuntu:22.04

    apt_packages:
    - graphviz
    - flatbuffers-compiler
    - protobuf-compiler
    - cmake
    - build-essential

    cri_home: { from: env, name: CRI_HOME }
    cri_root: { from: env, name: CRI_ROOT }
    cri_bin: { from: env, name: CRI_BIN }
    cri_run: { from: env, name: CRI_RUN }
    cri_run_args: { from: env, name: CRI_RUN_ARGS }
    cri_proj_path: { from: env, name: CRI_PROJ_PATH }
    root_drive: { from: env, name: ROOT_DRIVE }
    # Note: A bit hacky, but req'd for the moment.
    pypa_getpip_url: nil
    python_embed_zip_url: nil

    inner:
      alias: venv
      builder: venv
      platform: linux
      init: init-venv.sh
      run: run-venv.sh

      python: { from: env, name: SYSTEM_PYTHON }
      python_venv_prefix: { from: env, name: PYTHON_VENV_PREFIX }

      inner:
        alias: python
        builder: python
        platform: linux
        init: init-python.sh
        run: run-python.sh

        
        python_pkg_path: { from: env, name: PYTHON_PKG_PATH }
        python_autoinstall_path: { from: env, name: PYTHON_AUTOINSTALL_PATH }

        ps1_tag: { from: env, name: PS1_TAG }
        python: { from: env, name: VENV_PYTHON }
        pip_idx_args: { from: env, name: PIP_IDX_ARGS }
        pip_upstream_verifiers: { from: env, name: PIP_UPSTREAM_VERIFIERS }
        venv_python: { from: env, name: VENV_PYTHON }
        py_constraints: { from: env, name: PY_CONSTRAINTS }
        py_reqs: { from: env, name: PY_REQS }
        pkg_skip_list: { from: env, name: PKG_SKIP_LIST }
